{{- $secret := .Values.secret | default dict }}
{{- if and $secret.create $secret.hf_token }}
apiVersion: v1
kind: Secret
metadata:
  name: huggingface-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  HF_TOKEN: {{ $secret.hf_token | b64enc | quote }}
{{- end }}
